### ISSUE TITLE
Executables?

### ISSUE THREAD

**Issue by SzotsGabor** [ArjunBasandrai/shuffle-chess-engine#3]
Hello Arjun,

I have successfully compiled Shuffle 1.1 and plan to run a gauntlet for inclusion is the CCRL blitz list.

However, most users will need a downloadable exe to use your engine and I haven't found one in the zip file.

Gabor Szots
CCRL testing group

**Comment by ArjunBasandrai** [comment]
Hey Gabor,

I hope you're doing well. I wanted to let you know that I've included the executable file for Shuffle 1.1 in the main directory. The exe is named `shuffle.exe`.

If you have any further questions or need additional information, please feel free to reach out. Good luck with the testing, and I hope Shuffle 1.1 performs well in the CCRL blitz list!

Best regards,
Arjun Basandrai

**Comment by SzotsGabor** [comment]
Oh, I see. I have found it. I expected it to be included with 'Assets'.

However, the exe you provide behaves differently from the one which I compiled. Upon issuing uci from the command line, it displays this:

uci
id name Shuffle 1.1
id author Arjun Basandrai
option name Hash type spin default 64 min 4 max 1024
uciok

On the other hand, the exe I compiled displays this:

id name Shuffle 1.1
id author Arjun Basandrai
uciok
position startpos
8  r n b q k b n r
7  p p p p p p p p
6  . . . . . . . .
5  . . . . . . . .
4  . . . . . . . .
3  . . . . . . . .
2  P P P P P P P P
1  R N B Q K B N R

   a b c d e f g h

   Side: white
   Enpassant: NO
   Castling: KQkq
   Hash Key: 6ed57b118ae99580

**Comment by ArjunBasandrai** [comment]
Yeah, I had added a couple of debugging print statements earlier which have now been removed.

Also the exe provided showed wrong version number (i.e. 1.1) earlier. The current version is 1.2 and has been updated in the exe provided. 

I am currently preparing the release notes for v1.2 and they will be ready very soon. (The code is updated though and is ready for use)

I'd really appreciate it if you could use this newer version for your testing.

Thanks and regards,
Arjun

**Comment by SzotsGabor** [comment]
Please note that I made a mistake when providing the outputs. I edited the comment above. The difference is still big, e.g. the exe you provide displays 'time 0' at  all depths.

**Comment by ArjunBasandrai** [comment]
Yeah, it does seem to have a that bug. I will fix it and get back to you as soon as possible.

In the meanwhile can you share the details of the system you tested it on?

**Comment by ArjunBasandrai** [comment]
I have fixed the bug now, there seemed to be a data specifier mismatch for printing nodes value. 
It has been fixed now and shows the time correctly

Thank you so much for pointing out this bug!
Do let me know if there are any further issues or questions.

**Comment by ArjunBasandrai** [comment]
So sorry for deleting the comment.
Didn't mean to do it. I was trying to delete my previous comment, but accidentally deleted yours in the process 😬

**Comment by ArjunBasandrai** [comment]
Kindly test the latest version and let me know if the issue persists

**Comment by SzotsGabor** [comment]
Now the only issue I can see is the mismatch between version numbers at various places. Release 1.1 contains 1.1 sources but 1.2 exe. Quite confusing and may lead to mistakes.

**Comment by ArjunBasandrai** [comment]
Sorry, I didn't fully understand your comment. Do you mean that the current version has 1.2 exe but 1.1 in the source code?
Because from my side I have changed the source code to display 1.2 only and pushed it to the repo

**Comment by SzotsGabor** [comment]
> Kindly test the latest version and let me know if the issue persists

Latest exe is OK as far as displaying time is concerned. I'm going to start a tournament in the next couple of days.

**Comment by ArjunBasandrai** [comment]
Okay! Thanks for taking interest in my engine! In the next couple of weeks, I will be making some further improvements to the engine for example adding opening books, modifying evaluation function for open files, pawn structure etc. 

Also, I am super excited to hear about the results from your tests of the current version! Kindly let me know when they are out!

**Comment by SzotsGabor** [comment]
> Sorry, I didn't fully understand your comment. Do you mean that the current version has 1.2 exe but 1.1 in the source code? Because from my side I have changed the source code to display 1.2 only and pushed it to the repo

I am talking about the sources at 'Assets'. They are 1.1 sources while the provided exe is 1.2. That's confusing.

From my point of view the best solution would be releasing v1.2 as a new release so that its sources and exe are kept together at the same place, 'Assets'.

**Comment by ArjunBasandrai** [comment]
Okay! Thanks so much for your kind suggestion! I will surely do these changes in a short while

**Comment by ArjunBasandrai** [comment]
Okay, so you mean hat they will most likely be posted on the next week's update?
Also, I'll make sure to check the CCRL blitz list regularly!

**Comment by SzotsGabor** [comment]
> Okay, so you mean hat they will most likely be posted on the next week's update?

Yes. As things stand I won't be able to start my testing before Friday.

My usual procedure is to do a test gauntlet against about 15 engines, 32 games per match. After the list is updated I run another corrective test so that the error margins won't exceed 20. Altogether about 900 games will be played.
After that I'm going to use your engine only as an opponent for another engine.

When a new version is released the same procedure is repeated with that version. Of course, because I have lots of engines to test, I cannot promise I will test all your released versions.
